In [1]:
import numpy as np
import pandas as pd

In [2]:
dataset = pd.read_csv ("Dataset_Transaksi.csv")
x=dataset.iloc[:,[2,3]].values
y=dataset.iloc[:,-1].values

In [3]:
print(x)

[[    36  58470]
 [    20 144700]
 [    20  54997]
 [    25 116273]
 [    22 129683]
 [    29 102621]
 [    24 146419]
 [    33 139826]
 [    22 127793]
 [    20  83564]
 [    37  90642]
 [    33  84662]
 [    36  73891]
 [    26  78940]
 [    28 119426]
 [    22  91380]
 [    34 116245]
 [    30 115237]
 [    38  64602]
 [    38 129485]
 [    16 104124]
 [    38 101129]
 [    16 122981]
 [    23 100974]
 [    17 147746]
 [    23  61909]
 [    36 131739]
 [    26  70315]
 [    28 132073]
 [    31 105265]
 [    25 140525]
 [    32 134563]
 [    32 119480]
 [    29  92913]
 [    20 117891]
 [    15 125106]
 [    34  61813]
 [    35 100349]
 [    35  60673]
 [    29 149173]
 [    34 120289]
 [    23  63117]
 [    33 113253]
 [    15 118111]
 [    27 138223]
 [    32  80646]
 [    26  70626]
 [    36 148094]
 [    34 121653]
 [    23 149845]
 [    17  55801]
 [    15  79350]
 [    31  99717]
 [    33 139002]
 [    36 130854]
 [    25  91752]
 [    15 131267]
 [    34 111278]
 [    28 14517

In [4]:
print(y)

[1 0 1 0 0 0 0 1 1 0 0 0 1 1 0 0 1 1 1 1 0 1 1 1 1 0 0 0 1 0 1 1 0 0 1 0 0
 1 1 1 1 1 0 1 0 1 0 1 1 0 0 1 1 0 1 0 1 1 0 1 0 1 0 0 0 1 1 1 0 0 0 1 0 0
 0 0 1 0 0 1 1 1 0 0 1 1 0 1 0 0 0 0 1 1 0 1 0 1 1 0]


In [5]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.25,random_state=0)

In [6]:
print(x_train)

[[    34 121653]
 [    24 146419]
 [    21 104721]
 [    38 141106]
 [    27 108576]
 [    15 101662]
 [    40 120199]
 [    34 137437]
 [    23 148597]
 [    15  79350]
 [    26  70315]
 [    38  64602]
 [    15 131267]
 [    29 119461]
 [    23 111123]
 [    20 144700]
 [    17  96732]
 [    33 113253]
 [    23  63117]
 [    22 129683]
 [    22  91380]
 [    30 115237]
 [    34 120289]
 [    35  60673]
 [    29 102621]
 [    29 105505]
 [    31  86830]
 [    36  58470]
 [    20 117891]
 [    28 132073]
 [    17  55801]
 [    33  84662]
 [    15 125106]
 [    23 100974]
 [    31  99717]
 [    37  90642]
 [    32 134563]
 [    39 145081]
 [    34 111278]
 [    37  99709]
 [    23 108851]
 [    32 119480]
 [    33  81541]
 [    28 119426]
 [    40  96766]
 [    38 129485]
 [    31 105265]
 [    23 149845]
 [    21  50640]
 [    18  92978]
 [    22 147601]
 [    16 104124]
 [    33  99549]
 [    38 101348]
 [    22  97571]
 [    23  61909]
 [    35 100349]
 [    37  53030]
 [    26  7062

In [7]:
print(x_test)

[[    36 131739]
 [    33 128442]
 [    20  54997]
 [    25  91752]
 [    32  66723]
 [    18 132078]
 [    34 116245]
 [    35 100933]
 [    36 130854]
 [    40  70723]
 [    33 139002]
 [    40  78392]
 [    32 102744]
 [    26  78940]
 [    33 139826]
 [    25 140525]
 [    16 122981]
 [    17 147746]
 [    29  92913]
 [    22 127793]
 [    15 118111]
 [    20 101355]
 [    25 116273]
 [    40  50351]
 [    32  80646]]


In [8]:
print(y_train)

[1 0 0 0 1 0 1 0 0 1 0 1 1 0 0 0 1 0 1 0 0 1 1 1 0 0 1 1 1 1 0 0 0 1 1 0 1
 1 1 1 1 0 1 0 0 1 0 0 1 1 0 0 0 0 0 0 1 1 0 1 1 0 1 0 0 1 0 1 0 0 0 1 0 1
 0]


In [9]:
print(y_test)

[0 0 1 0 0 1 1 0 1 1 0 1 0 1 1 1 1 1 0 1 1 0 0 1 1]


In [11]:
from pandas.core.common import standardize_mapping
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
x_train = sc.fit_transform(x_train)
x_test = sc.fit_transform(x_test)

In [12]:
print(x_test)

[[ 0.96366589  0.89739197]
 [ 0.57509094  0.78024185]
 [-1.10873388 -1.82943082]
 [-0.46110895 -0.52343968]
 [ 0.44556595 -1.4127786 ]
 [-1.36778385  0.90943743]
 [ 0.70461592  0.34685391]
 [ 0.83414091 -0.19721728]
 [ 0.96366589  0.86594585]
 [ 1.48176584 -1.27064925]
 [ 0.57509094  1.15546335]
 [ 1.48176584 -0.99815174]
 [ 0.44556595 -0.13286821]
 [-0.33158396 -0.97868001]
 [ 0.57509094  1.184742  ]
 [-0.46110895  1.2095791 ]
 [-1.62683382  0.58619974]
 [-1.49730884  1.46615813]
 [ 0.05699099 -0.48218664]
 [-0.84968391  0.75718136]
 [-1.75635881  0.41315725]
 [-1.10873388 -0.18222263]
 [-0.46110895  0.34784881]
 [ 1.48176584 -1.99451406]
 [ 0.44556595 -0.91806184]]


In [14]:
from sklearn.naive_bayes import GaussianNB
classifier = GaussianNB()
classifier.fit(x_train,y_train)

GaussianNB()

In [15]:
y_pred = classifier.predict(x_test)

In [16]:
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test,y_pred)

In [17]:
print(cm)


[[ 8  2]
 [10  5]]


In [20]:
var1=8
var2=5
var3=2
var4=10
hasil = (var1+var2)/(var1+var2+var3+var4)*100

In [21]:
print(hasil)

52.0
